version: '3.8' 
services:
  app:
    # image: dreamhartley705/jimihub:latest
    image: node:lts-slim
    container_name: jimihub
    working_dir: /app  
    #ports:
    #  - "3000:3000"
    volumes:
      - ./:/app          # 현재 디렉토리 전체를 /app에 마운트
      # - ./data:/app/data
    command: /bin/sh -c "npm install --only=production && npm start"
    #env_file:
      #- .env
    environment:
      # 호스트 쉘 환경 변수의 값을 가져와 컨테이너에 전달
      - PORT=${PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL}
    networks:
      - dokploy-network
      
networks:
  dokploy-network:
    external: true
