version: '3.8' 
services:
  jimihub:
    image: node:lts-slim
    # container_name: jimihub
    working_dir: /app  
    volumes:
      - ./:/app  
      - ../files/database.db:/app/data/database.db:rw
    command: /bin/sh -c "apt update && apt install sqlite3 -y && npm install --only=production && npm start"
    environment:
      # 호스트 쉘 환경 변수의 값을 가져와 컨테이너에 전달
      - PORT=${PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - GEMINI_BASE_URL=${GEMINI_BASE_URL}
    networks:
      - dokploy-network
  
networks:
  dokploy-network:
    external: true
    
